apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "sealedsecrets.name" . }}-secrets-controller
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "sealedsecrets.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "sealedsecrets.name" . }}-unsealer
subjects:
- kind: ServiceAccount
  name: {{ template "sealedsecrets.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}