apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: ce
spec:
  ports:
  - port: {{ .Values.service.spec.ports.port }}
    targetPort: {{ .Values.service.spec.ports.targetPort }}
  selector:
    name: sealed-secrets-controller
  type: {{ .Values.service.spec.type }}