apiVersion: v2
appVersion: 1.0.0
version: 1.0.0
name: sealed-secrets
description: SealedSecrets by bitnami for cloud engineering team
type: application
maintainers:
  - name: Logan Clemons
    email: loganrobertclemons@gmail.com
