namespace: kube-system

serviceAccount:
  name: sealed-secrets-controller

service:
  spec:
    ports:
      type: ClusterIP
      port: 8080
      targetPort: 8080

sealedSecrets:
  spec:
    replicas: 1
    type: RollingUpdate
    revisionHistoryLimit: 10
    image:
      name: quay.io/bitnami/sealed-secrets-controller
      tag: v0.16.0
      pullPolicy: IfNotPresent