namespace: ce

serviceAccount:
  name: sealed-secrets-controller

service:
  spec:
    ports:
      type: ClusterIP
      port: 8080
      targetPort: 8080

sealedSecrets:
  spec:
    replicas: 1
    type: RollingUpdate
    revisionHistoryLimit: 10
    image:
      name: lirio-docker.jfrog.io/ce-sealed-secrets
      tag: 1.0.0
      pullPolicy: IfNotPresent