apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sealedsecrets.serviceAccountName" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "sealedsecrets.name" . }}
  namespace: {{ .Values.namespace }}